export const ADD_ITEM = "ADD_ITEM"
export const ADD_TABLE = "ADD_TABLE"
export const REMOVE_TABLE = "REMOVE_TABLE"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const EDIT_ITEM = "EDIT_ITEM"
export const TOGGLE_ADD_ITEM = "TOGGLE_ADD_ITEM"
export const PASS_TABLE_ID = "PASS_TABLE_ID"
export const UNSET_TABLE_ID = "UNSET_TABLE_ID"
