export const ADD_ITEM = "ADD_ITEM"
export const ADD_TABLE = "ADD_TABLE"
export const REMOVE_ITEM = "REMOVE_ITEM"
export const EDIT_ITEM = "EDIT_ITEM"
export const TOGGLE_ADD_ITEM = "TOGGLE_ADD_ITEM"
export const TOGGLE_ADD_TABLE = "TOGGLE_ADD_TABLE"
